### ISSUE TITLE
make  nf_test  tst_f90 failing to link to libnetcdf

### ISSUE THREAD

**Issue by simonholgate** [Unidata/netcdf-fortran#122]
Hi,

I'm going crazy. I can't get netcdf-fortran 4.4.5 to `make check`.

I've installed parallel netcdf 1.9.0 with mpi and `--enable-relax-coord-bound`. 

I've set `LD_LIBRARY_PATH` but running `make check` fails with:

> Making check in nf_test
> make[1]: Entering directory '/tmp/netcdf-fortran-4.4.5/nf_test'                 make  nf_test         tst_f90
> make[2]: Entering directory '/tmp/netcdf-fortran-4.4.5/nf_test'
> /bin/bash ../libtool  --tag=F77   --mode=link mpif77 -I../fortran  -g -O2  -L/usr/local/lib -L/usr/local/lib -L/usr/lib -o nf_test f03lib_f_interfaces.o test_ge
> t.o test_put.o nf_error.o nf_test.o test_read.o test_write.o util.o f03lib.o ../
> fortran/libnetcdff.la -lhdf5_hl -lhdf5 -lz -lcurl -lm -ldl -lmpi
> libtool: link: mpif77 -I../fortran -g -O2 -o nf_test f03lib_f_interfaces.o test_
> get.o test_put.o nf_error.o nf_test.o test_read.o test_write.o util.o f03lib.o
> -L/usr/local/lib -L/usr/lib ../fortran/.libs/libnetcdff.a -L/tmp/build-mpich-3.2
> .1/src/mpl /usr/local/lib/libhdf5_hl.so /usr/local/lib/libhdf5.so -lz /usr/lib/x
> 86_64-linux-gnu/libcurl.so -lm -ldl /usr/local/lib/libmpi.so -lrt -lpthread -pth
> read
> ../fortran/.libs/libnetcdff.a(nf_attio.o): In function `nf_put_att_text_':
> /tmp/netcdf-fortran-4.4.5/fortran/nf_attio.F90:59: undefined reference to `nc_pu
> t_att_text'
> ...
> ../fortran/.libs/libnetcdff.a(nf_varsio.o): In function `nf_get_vars_':
> /tmp/netcdf-fortran-4.4.5/fortran/nf_varsio.F90:1081: undefined reference to `nc_get_vars'
> collect2: error: ld returned 1 exit status
> Makefile:1285: recipe for target 'nf_test' failed

So it's clearly not finding `libnetcdf`yet:
`echo $LD_LIBRARY_PATH` gives:
`/usr/lib:/usr/local/lib:/tmp/netcdf-fortran-4.4.5`

And:
`nm /usr/local/lib/libnetcdf.a | grep nc_get_vars` gives:

>                  U nc_get_vars
> 0000000000001e17 T nc_get_vars
> ...
> 0000000000002200 T nc_get_vars_ulonglong
> 0000000000002119 T nc_get_vars_ushort

What am I missing? 

config.log is attached.

System is Debian Jessie running mpich 3.2.1 with gcc 4.9.2-10. Same behaviour on Debian Stretch with gcc 6.3.0-18.
[config.log](https://github.com/Unidata/netcdf-fortran/files/2859708/config.log)

netcdf-c was built with --disable-shared --enable-parallel-tests --enable-pnetcdf 

Many thanks!

**Comment by simonholgate** [comment]
I'm attaching the output of `nc-config --all`.
[nc-config.out.txt](https://github.com/Unidata/netcdf-fortran/files/2859921/nc-config.out.txt)

**Comment by edhartnett** [comment]
I have just done a lot of work on the netcdf-fortran build - commits were just merged with master.

So can I ask you to check out master and build from that? Let me know if you need help doing that.

**Comment by simonholgate** [comment]
Thanks. I will do.

The problem goes away if I drop `--disable-shared` in `netcdf-c`. That means I have to recompile `pnetcdf` with `-fPIC` but otherwise it seems fine.

I'll report back when I've built the latest commit.

**Comment by simonholgate** [comment]
I can confirm that commit `8924b2d` also fails with `--disable-shared`.

**Comment by edhartnett** [comment]
I am building a static stack right now for my CI system...

**Comment by edhartnett** [comment]
OK, my static only build is failing like this:

```
/bin/bash ../libtool  --tag=F77   --mode=link gfortran -I../fortran  -g -O2  -L/usr/local/netcdf-c-4.6.2_static/lib -o nf_test f03lib_f_interfaces.o test_get.o test_put.o nf_error.o nf_test.o test_read.o test_write.o util.o f03lib.o ../fortran/libnetcdff.la -ldl -lz -lcurl -lm 
libtool: link: gfortran -I../fortran -g -O2 -o .libs/nf_test f03lib_f_interfaces.o test_get.o test_put.o nf_error.o nf_test.o test_read.o test_write.o util.o f03lib.o  -L/usr/local/netcdf-c-4.6.2_static/lib ../fortran/.libs/libnetcdff.so -ldl -lz /usr/lib/x86_64-linux-gnu/libcurl-nss.so -lm -pthread
../fortran/.libs/libnetcdff.so: undefined reference to `nc_put_vara_short'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_get_vara_short'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_get_att_float'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_get_vara_schar'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_inq_attname'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_set_default_format'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_inq_dimname'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_get_vara_double'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_put_vara_text'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_put_var_schar'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_inq_dim'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_put_vars_schar'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_open_mem'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_inq_nvars'
../fortran/.libs/libnetcdff.so: undefined reference to `nc_get_varm_float'
...
```

Stand by while I sort this out...

**Comment by edhartnett** [comment]
OK, I got the static build to work without any changes, but there are some issues. But first, let's see if we can get it working for you.

For static builds, the location of all the libraries needs to be specified in the LDFLAGS.

So for me, it works when I do this:
`CFLAGS='-g -Wall' CPPFLAGS='-I/usr/local/zlib-1.2.11/include -I/usr/local/szip-2.1.1_static/include -I/usr/local/hdf5-1.10.4_static/include' LDFLAGS='-L/usr/local/zlib-1.2.11/lib -L/usr/local/szip-2.1.1_static/lib -L/usr/local/hdf5-1.10.4_static/lib' ./configure --prefix=/usr/local/netcdf-c-4.6.2_static  --disable-shared && make -j check`

Note that I have a -L argument for netcdf-c, hdf5, zlib, and szlib. If any of those are missing, the build mysteriously breaks.

So please try that. If it doesn't work post your config.log file and I will take a look.

I will also take a look at making these failures occur in the configure script instead of at link-time.

@wkliao it is awkward that pnetcdf defies convention and builds static libraries by default. To get pnetcdf to build shared, used --enable-shared when configuring pnetcdf.

**Comment by simonholgate** [comment]
Aarghh! I was missing `-L/usr/lib/x86_64-linux-gnu` from LDFLAGS.

Problem solved. Thanks for making me look for zlib - which is what made me realise the error.

**Comment by edhartnett** [comment]
I have modified the build so that this case will fail in configure instead of at link-time. PR will be up shortly.

**Comment by wkliao** [comment]
@edhartnett 
PnetCDF is developed with the goal of achieving high-performance parallel I/O.
Because shared libraries may introduce delays in application launch times, we have always been recommending our users to use static libraries.

**Comment by edhartnett** [comment]
@wkliao I would like to see some indication of actual delays in launch times. Has this been measured?

**Comment by WardF** [comment]
@wkliao I'm curious as well, but if I'm being honest it's because of my personal preference for shared libraries.  I'd be curious to see the literature/benchmarks on this, thanks!

**Comment by edhartnett** [comment]
This issue has been resolved, and the build improved so that we can more readily detect this condition. This ticket should be closed.

**Comment by wkliao** [comment]
Loading functions in shared libraries at the run time may require to access the file system.
On HPC platforms, compute nodes and storage servers are physically located on different cabinets.

Also see "Performance Implications of Using Dynamic Shared Objects" in http://www.nersc.gov/users/computational-systems/edison/running-jobs/shared-and-dynamic-libraries

**Comment by simonholgate** [comment]
Thanks for your help. I should confirm that 4.4.5 still appears to have the linking issue originally raised but it is resolved in the latest commit.

I'll close the issue.
